name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  provision_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        working-directory: infra
        run: terraform init

      - name: Planejar Terraform
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Aplicar Terraform
        working-directory: infra
        run: terraform apply -auto-approve tfplan

  deploy_lambda:
    runs-on: ubuntu-latest
    needs: provision_infra

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar dependências necessárias
        run: sudo apt-get update && sudo apt-get install -y xz-utils zip

      - name: Construir pacote de implantação
        run: make build

      - name: Implantar a AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name LambdaProcessadorVideos \
            --zip-file fileb://deployment_package.zip

      - name: Limpeza pós-deploy
        run: make clean

      - name: Notificar sucesso do deploy
        if: success()
        run: echo "Deploy concluído com sucesso!"

      - name: Notificar falha do deploy
        if: failure()
        run: echo "Falha no deploy!"